Feature/course 1 Create an Initial Website Mockup Final version .
ubiqum/ubiqum-bootcamp pull request #27
Opened 2021-09-17 01:42 UTC by grojas123

Feature/course 1 Create an Initial Website Mockup Final version .

2021-09-21 20:15 UTC, grojas123 commented
Created the 3 version of the site with css ubiqum-bootcamp\staff\gustavo-rojas\course-1 in nysl_[1,2,3]_css

2021-09-22 12:17 UTC, manuelbarzi commented
hi gustavo
your three design projections seem to work fine (tested them in my local machine)
just a few comments
- you are using `id` selectors in css for everything. even though this is working, it is not the best practice to use them, but class selectors. moreover, it is a good practice that you learn a good methodology to organise the css styles in your file. pay attention to the resources shared today in our discord channel. there you will find a demo we did about BEM, which might be useful for you to do better css coding. so i encourage you to create new versions of your styles working with class selectors and BEM methodology. you can create new folders for those new versions.
- another thing to point out is the challenge of creating one single html and multiple css designs. that's the real challenge here. we shared resources about this in the discord channel too in the past days. pay attention to the CSS Zen Garden idea (this demo is The Demo of the web about this topic).

2021-09-24 18:35 UTC, grojas123 commented
Esta es la version de la tarea 1 . La hice con CSS para ir adelatando la siguiente tarea .

2021-09-27 16:26 UTC, elolivier requested changes

2021-09-27 16:26 UTC, elolivier commented on staff/gustavo-rojas/course-1-new-version/about.html
> +  <link rel="stylesheet" href="styles/nctss_1.css">
Please, use only tools related to Task 1, no CSS.

2021-09-27 21:11 UTC, grojas123 commented
Updated the \staff\gustavo-rojas\course-1-new-version\task1 with no usage of FlexBox with nctss_1.css

2021-09-28 04:40 UTC, grojas123 commented
Task2 Final Version of \staff\gustavo-rojas\course-1-new-version\task2 with usage of FlexBox with nctss_[1,2,3].css Tested done

2021-09-28 16:54 UTC, closed without merging

2021-09-28 16:54 UTC, grojas123 commented
I need to fix the nctss_3.css