Feature/course 1
ubiqum/ubiqum-bootcamp pull request #32
Opened 2021-09-27 17:47 UTC by SGInim

PR (Pull Request) #1

According to what we have discussed with Ernesto, this Pull Request includes task1 and git

2021-09-29 15:41 UTC, elolivier commented on staff/sergi-pallice/course-1/Task1/contact.html
> +<p>Please email us at info@nctts.org</p>
This should go inside a div and image 3 is missing. Also email should be a link to the email.

2021-09-29 16:04 UTC, elolivier requested changes

2021-09-29 16:04 UTC, elolivier commented on staff/sergi-pallice/course-1/Task1/about.html
> +    <img src="Images/Image-2.png" class="soccer1"/>
Use same class for images in all pages in order to display them equal, class soccer1 doesn't exist on styles.css

2021-09-29 16:04 UTC, elolivier commented on staff/sergi-pallice/course-1/Task1/index.html
> +  <img src="Images/Image-1.png" class="logo"/>
Same as about image, if you are going to use class logo, use it on every image.

2021-09-29 16:04 UTC, elolivier commented on staff/sergi-pallice/course-1/Task1/styles.css
> +.index-frame2 img {
Same code that index-frame1 img, why two classes?

2021-09-29 16:05 UTC, elolivier commented
Please review my comments

2021-10-05 17:04 UTC, SGInim commented on staff/sergi-pallice/course-1/Task1/about.html
> +    <img src="Images/Image-2.png" class="soccer1"/>
Fixed

2021-10-06 17:18 UTC, elolivier approved these changes

2021-10-06 17:19 UTC, merged