Feature/course 2 task 2
ubiqum/ubiqum-bootcamp pull request #51
Opened 2021-10-31 23:37 UTC by grojas123

All the tasks Done even the optionals .

2021-11-02 19:10 UTC, elolivier requested changes

2021-11-02 19:10 UTC, elolivier commented on staff/gustavo-rojas/task2/tgif-project/scripts/html.js
> +*/
This comment is no needed, please delete it.

2021-11-02 19:10 UTC, elolivier commented on staff/gustavo-rojas/task2/tgif-project/scripts/html.js
> +//* This is for if we need to wait the to the date to be storage on jsonsenators  .
Please rephrase this comment, I'm not sure what is the message.

2021-11-02 19:27 UTC, grojas123 commented on staff/gustavo-rojas/task2/tgif-project/scripts/html.js
> +*/
Removed

2021-11-02 19:27 UTC, grojas123 commented on staff/gustavo-rojas/task2/tgif-project/scripts/html.js
> +//* This is for if we need to wait the to the date to be storage on jsonsenators  .
rephrase done .

2021-11-02 19:27 UTC, grojas123 commented
Done.

2021-11-03 18:00 UTC, elolivier approved these changes

2021-11-03 18:00 UTC, merged